#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "$0")" && pwd)"
skills_dir="$root_dir/skills/sourcelens-qa"
env_dir="${SOURCELENS_HOME:-$HOME/.sourcelens}"
env_file="$env_dir/env"

client=""
url="${SOURCELENS_MCP_URL:-}"
api_key="${SOURCELENS_API_KEY:-}"
register_mcp=1

usage() {
  cat >&2 <<'EOF'
usage: install.sh [all|codex|claude] [--client all|codex|claude]
       [--url URL] [--api-key KEY] [--no-mcp]

  --client   install target: codex, claude, or all (default: all)
  --url      SourceLens MCP gateway URL (prompted when omitted)
  --api-key  SourceLens API key (prompted when omitted)
  --no-mcp   install the Skill and CLI without configuring credentials or MCP
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --client) client="${2:?--client requires a value}"; shift 2 ;;
    --url) url="${2:?--url requires a value}"; shift 2 ;;
    --api-key) api_key="${2:?--api-key requires a value}"; shift 2 ;;
    --no-mcp) register_mcp=0; shift ;;
    -h|--help) usage; exit 0 ;;
    codex|claude|all) client="$1"; shift ;;
    *) echo "unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

client="${client:-all}"
case "$client" in
  codex|claude|all) ;;
  *) usage; exit 2 ;;
esac

if [ "$register_mcp" = "1" ] && [ -z "$url" ]; then
  if [ ! -t 0 ]; then
    echo "error: --url is required" >&2
    exit 2
  fi
  read -r -p "SourceLens MCP gateway URL [http://localhost:8000]: " url || true
  url="${url:-http://localhost:8000}"
fi

if [ "$register_mcp" = "1" ] && [ -z "$api_key" ]; then
  if [ ! -t 0 ]; then
    echo "error: --api-key is required" >&2
    exit 2
  fi
  read -r -s -p "SourceLens API key: " api_key || true
  echo
  if [ -z "$api_key" ]; then
    echo "error: --api-key is required" >&2
    exit 2
  fi
fi

write_env() {
  mkdir -p "$env_dir"
  chmod 700 "$env_dir"
  (
    umask 077
    {
      echo "# Generated by sourcelens install. Do not commit."
      printf 'export SOURCELENS_MCP_URL=%q\n' "$url"
      printf 'export SOURCELENS_API_KEY=%q\n' "$api_key"
    } > "$env_file"
  )
  chmod 600 "$env_file"
  echo "Wrote SourceLens credentials to $env_file"
}

install_cli() {
  mkdir -p "$env_dir/client/bin" "$env_dir/client/skills/sourcelens-qa" "$env_dir/bin"
  env_dir="$(cd "$env_dir" && pwd)"
  env_file="$env_dir/env"
  # The installed CLI can run install again from its own persistent package.
  if [ ! "$root_dir" -ef "$env_dir/client" ]; then
    cp "$root_dir/bin/sourcelens.js" "$env_dir/client/bin/sourcelens.js"
    cp "$root_dir/install.sh" "$env_dir/client/install.sh"
    cp "$skills_dir/SKILL.md" "$skills_dir/mcp.json" "$env_dir/client/skills/sourcelens-qa/"
  fi
  chmod +x "$env_dir/client/bin/sourcelens.js"
  ln -sf ../client/bin/sourcelens.js "$env_dir/bin/sourcelens"
  echo "Installed SourceLens CLI at $env_dir/bin/sourcelens"
}

register_profile() {
  local profile="${SOURCELENS_PROFILE:-}"
  if [ -z "$profile" ]; then
    case "$(basename "${SHELL:-sh}")" in
      bash) profile="$HOME/.bashrc" ;;
      zsh) profile="$HOME/.zshrc" ;;
      *) profile="$HOME/.profile" ;;
    esac
  fi
  mkdir -p "$(dirname "$profile")"
  local env_line path_line
  printf -v env_line '[ ! -f %q ] || . %q' "$env_file" "$env_file"
  printf -v path_line 'export PATH=%q:"$PATH"' "$env_dir/bin"
  for line in "$env_line" "$path_line"; do
    if [ ! -f "$profile" ] || ! grep -qxF "$line" "$profile"; then
      printf '\n%s\n' "$line" >> "$profile"
    fi
  done
  echo "Linked SourceLens CLI and env in $profile"
}

install_codex() {
  target="${CODEX_HOME:-$HOME/.codex}/skills/sourcelens-qa"
  mkdir -p "$target"
  cp "$skills_dir/SKILL.md" "$target/SKILL.md"
  cp "$skills_dir/mcp.json" "$target/mcp.json"
  echo "Installed SourceLens Q&A Skill for Codex at $target"
}

install_claude() {
  target="${CLAUDE_HOME:-$HOME/.claude}/skills/sourcelens-qa"
  mkdir -p "$target"
  cp "$skills_dir/SKILL.md" "$target/SKILL.md"
  cp "$skills_dir/mcp.json" "$target/mcp.json"
  echo "Installed SourceLens Q&A Skill for Claude at $target"
}

register_codex_mcp() {
  if ! command -v codex >/dev/null 2>&1; then
    echo "codex CLI not found; register the MCP server manually in ${CODEX_HOME:-$HOME/.codex}/config.toml"
    return
  fi
  codex mcp add sourcelens-qa \
    --url "$url" \
    --bearer-token-env-var SOURCELENS_API_KEY >/dev/null
  echo "Registered MCP server 'sourcelens-qa' for Codex (reads SOURCELENS_API_KEY at launch)"
}

register_claude_mcp() {
  if ! command -v claude >/dev/null 2>&1; then
    echo "claude CLI not found; register the MCP server manually with 'claude mcp add'"
    return
  fi
  claude mcp remove sourcelens-qa --scope user >/dev/null 2>&1 || true
  claude mcp add sourcelens-qa \
    --scope user \
    --transport http \
    "$url" \
    -H "Authorization: Bearer $api_key" >/dev/null
  claude_config="${CLAUDE_CONFIG_DIR:-$HOME}/.claude.json"
  [ -f "$claude_config" ] && chmod 600 "$claude_config"
  echo "Registered MCP server 'sourcelens-qa' for Claude in $claude_config"
}

install_cli
if [ "$register_mcp" = "1" ]; then
  write_env
fi
register_profile

case "$client" in
  codex) install_codex ;;
  claude) install_claude ;;
  all) install_codex; install_claude ;;
esac

if [ "$register_mcp" = "1" ]; then
  case "$client" in
    codex) register_codex_mcp ;;
    claude) register_claude_mcp ;;
    all) register_codex_mcp; register_claude_mcp ;;
  esac
fi

echo "Open a new shell to use sourcelens, or run $env_dir/bin/sourcelens directly."
