#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "$0")" && pwd)"
skills_dir="$root_dir/skills/sourcelens-qa"
legacy_home="$HOME/.sourcelens"
config_dir="${SOURCELENS_CONFIG_HOME:-${SOURCELENS_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/sourcelens}}"
data_dir="${SOURCELENS_DATA_HOME:-${SOURCELENS_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/sourcelens}}"
bin_dir="${SOURCELENS_BIN_HOME:-${SOURCELENS_HOME:+$SOURCELENS_HOME/bin}}"
bin_dir="${bin_dir:-${XDG_BIN_HOME:-$HOME/.local/bin}}"
env_file="$config_dir/env"

url="${SOURCELENS_BASE_URL:-}"
api_key="${SOURCELENS_API_KEY:-}"
store_credentials=1

usage() {
  cat >&2 <<'EOF'
usage: install.sh [--url URL] [--api-key KEY] [--no-auth]

  --url      SourceLens service base URL (prompted when omitted)
  --api-key  SourceLens API key (prompted when omitted)
  --no-auth  install the Skill and CLI without storing credentials

Layout follows the XDG base directory spec. Override with:
  SOURCELENS_CONFIG_HOME  credentials directory (default ~/.config/sourcelens)
  SOURCELENS_DATA_HOME    package directory (default ~/.local/share/sourcelens)
  SOURCELENS_BIN_HOME     executable directory (default ~/.local/bin)
  SOURCELENS_HOME         legacy single-directory layout (all of the above)
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --url) url="${2:?--url requires a value}"; shift 2 ;;
    --api-key) api_key="${2:?--api-key requires a value}"; shift 2 ;;
    --no-auth) store_credentials=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

if [ "$store_credentials" = "1" ] && [ -z "$url" ]; then
  if [ ! -t 0 ]; then
    echo "error: --url is required" >&2
    exit 2
  fi
  read -r -p "SourceLens service URL [http://localhost:8000]: " url || true
  url="${url:-http://localhost:8000}"
fi

if [ "$store_credentials" = "1" ] && [ -z "$api_key" ]; then
  if [ ! -t 0 ]; then
    echo "error: --api-key is required" >&2
    exit 2
  fi
  read -r -s -p "SourceLens API key: " api_key || true
  echo
  if [ -z "$api_key" ]; then
    echo "error: --api-key is required" >&2
    exit 2
  fi
fi

write_env() {
  mkdir -p "$config_dir"
  chmod 700 "$config_dir"
  (
    umask 077
    {
      echo "# Generated by sourcelens install. Do not commit."
      printf 'export SOURCELENS_BASE_URL=%q\n' "$url"
      printf 'export SOURCELENS_API_KEY=%q\n' "$api_key"
    } > "$env_file"
  )
  chmod 600 "$env_file"
  echo "Wrote SourceLens credentials to $env_file"
}

profile_path() {
  local profile="${SOURCELENS_PROFILE:-}"
  if [ -z "$profile" ]; then
    case "$(basename "${SHELL:-sh}")" in
      bash) profile="$HOME/.bashrc" ;;
      zsh) profile="$HOME/.zshrc" ;;
      *) profile="$HOME/.profile" ;;
    esac
  fi
  printf '%s' "$profile"
}

migrate_legacy() {
  [ -d "$legacy_home" ] || return 0
  if [ "$legacy_home" = "$config_dir" ] || [ "$legacy_home" = "$data_dir" ]; then
    return 0
  fi
  if [ -f "$legacy_home/env" ] && [ ! -f "$env_file" ]; then
    mkdir -p "$config_dir"
    chmod 700 "$config_dir"
    cp "$legacy_home/env" "$env_file"
    chmod 600 "$env_file"
    echo "Migrated SourceLens credentials from $legacy_home/env to $env_file"
  fi
  local profile tmp
  profile="$(profile_path)"
  if [ -f "$profile" ]; then
    tmp="$profile.sourcelens.tmp"
    grep -vF -e "$legacy_home/env" -e "$legacy_home/bin" "$profile" > "$tmp" || true
    mv "$tmp" "$profile"
  fi
  echo "SourceLens moved out of $legacy_home; remove it once migration is verified."
}

install_cli() {
  mkdir -p "$data_dir/bin" "$data_dir/skills/sourcelens-qa" "$bin_dir"
  data_dir="$(cd "$data_dir" && pwd)"
  # The installed CLI can run install again from its own persistent package.
  if [ ! "$root_dir" -ef "$data_dir" ]; then
    cp "$root_dir/bin/sourcelens.js" "$data_dir/bin/sourcelens.js"
    cp "$root_dir/install.sh" "$data_dir/install.sh"
    cp "$skills_dir/SKILL.md" "$data_dir/skills/sourcelens-qa/"
  fi
  chmod +x "$data_dir/bin/sourcelens.js"
  ln -sf "$data_dir/bin/sourcelens.js" "$bin_dir/sourcelens"
  echo "Installed SourceLens CLI at $bin_dir/sourcelens"
}

register_profile() {
  local profile
  profile="$(profile_path)"
  mkdir -p "$(dirname "$profile")"
  local env_line path_line
  printf -v env_line '[ ! -f %q ] || . %q' "$env_file" "$env_file"
  printf -v path_line 'export PATH=%q:"$PATH"' "$bin_dir"
  for line in "$env_line" "$path_line"; do
    if [ ! -f "$profile" ] || ! grep -qxF "$line" "$profile"; then
      printf '\n%s\n' "$line" >> "$profile"
    fi
  done
  echo "Linked SourceLens CLI and env in $profile"
}

install_codex() {
  target="${CODEX_HOME:-$HOME/.codex}/skills/sourcelens-qa"
  mkdir -p "$target"
  cp "$skills_dir/SKILL.md" "$target/SKILL.md"
  echo "Installed SourceLens Q&A Skill for Codex at $target"
}

install_claude() {
  target="${CLAUDE_HOME:-$HOME/.claude}/skills/sourcelens-qa"
  mkdir -p "$target"
  cp "$skills_dir/SKILL.md" "$target/SKILL.md"
  echo "Installed SourceLens Q&A Skill for Claude at $target"
}

migrate_legacy
install_cli
if [ "$store_credentials" = "1" ]; then
  write_env
fi
register_profile

install_codex
install_claude

echo "Open a new shell to use sourcelens, or run $bin_dir/sourcelens directly."
